### ISSUE TITLE
Incorrect key_path for sury preset

### ISSUE THREAD

**Issue by santiagomr** [systemli/ansible-role-apt_repositories#7]
Hi, first of all thanks for sharing.

The reason for this issue is to report a minor detail in the sury preset that generates an error in the execution of the role.

Here the correct file name is `sury.gpg` instead of `sury.asc`:

https://github.com/systemli/ansible-role-apt_repositories/blob/ed09af7c205d799e6775d0181073942f3fbd62ea/vars/sury.yml#L3

Regards

**Comment by t2d** [comment]
Thank you for bringing this to our attention. Please let me know if the fix still isn't sufficient.

**Comment by santiagomr** [comment]
Sorry for the delay.

I see in the commit that only the key binary file was updated. In addition to that, in the [vars/sury.yml](https://github.com/systemli/ansible-role-apt_repositories/blob/master/vars/sury.yml) file it's necessary to correct:
```yaml
key_path: sury.asc
```
by
```yaml
key_path: sury.gpg
```
